### ISSUE TITLE
Link Down Again

### ISSUE THREAD

**Issue by edessa** [fpv-iplab/rulstm#11] opened 2020-08-03 18:48 UTC
Hello,

I've been trying to use RULSTM as a baseline for a paper due next week, but unfortunately the download link to the dataset is down. Could you take a look at that please?

Thanks,
Eadom

**Comment by antoninofurnari** [comment] 2020-08-03 19:40
Hello Eadom,

We are having issues with the storage hosting the files, which will be hopefully replaced in Septemeber. The link is now up again, but it may go down and require manual intervention.

I'm keeping this issue open and plan to close it as soon as the problem is permanently solved. Feel free to bring this up again if the issue gets back.

Best,
Antonino

**Comment by edessa** [comment] 2020-08-03 19:48
> Hello Eadom,
> 
> We are having issues with the storage hosting the files, which will be hopefully replaced in Septemeber. The link is now up again, but it may go down and require manual intervention.
> 
> I'm keeping this issue open and plan to close it as soon as the problem is permanently solved. Feel free to bring this up again if the issue gets back.
> 
> Best,
> Antonino

Thank you so much! I'm downloading it now, hopefully it doesn't go down in the meantime...

**Comment by jinlongbin** [comment] 2020-12-29 02:44
Hello

The download link to the dataset is down.
Could you please check the link?

Thanks
Jin

**Comment by antoninofurnari** [comment] 2020-12-30 09:56
Hello,

Apologies for the problem. It should be up again. Hopefully, we are going to fix this and move the files to the a new server in January. Until then, I'm keeping the issue open.

Best,
Antonino

**Comment by antoninofurnari** [comment] 2021-01-30 09:41
We have finally migrated the files ro a new server. You should not experience any issue now. Thank you for your patience!

**Closed by antoninofurnari** 2021-01-30 09:41 UTC
